# Generated by Django 5.2 on 2026-03-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('home', 'Home & Kitchen'), ('sports', 'Sports & Fitness'), ('beauty', 'Beauty & Personal Care'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
