# Generated by Django 5.2 on 2026-03-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_app', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
